/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_ndk_NativaUtils */

#ifndef _Included_com_baidu_ndk_NativaUtils
#define _Included_com_baidu_ndk_NativaUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_ndk_NativaUtils
 * Method:    getTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_ndk_NativaUtils_getTime
  (JNIEnv *, jobject);


/*
 * Class:     com_baidu_ndk_NativaUtils
 * Method:    getTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baidu_ndk_NativaUtils_setJNIEnv
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
